FROM workshopbuild-interim

MAINTAINER Suchipi Izumi "me@suchipi.com"

ADD start-server.sh /start-server.sh
RUN mkdir -p /gmod-base/garrysmod/lua/autorun
ADD workshop.lua /gmod-base/garrysmod/lua/autorun/workshop.lua

ENV COLLECTION_ID=collection_id
ENV STEAM_WEB_KEY=steam_web_key
ENV GAMEMODE=gamemode
ENV MAP=map
ENV HOSTNAME="hostname"

EXPOSE 27015/udp
CMD ["/bin/sh", "/start-server.sh"]
